### ISSUE TITLE
Зачем отдельные методы? Разве нельзя их вызывать при добавлении? Или по требованию рассчитывать max?

### ISSUE THREAD

**Issue by coursar** [Eeenkeeei/shopping-list#5]
https://github.com/Eeenkeeei/shopping-list/blob/a12051a0e448c7f10ada425ade2c53b2ec93185b/src/js/lib.js#L44-L61

**Comment by Eeenkeeei** [comment]
методы удалены: c7673765c847fc033a4c8fdea9d6d32b5cdd7aba
